package com.mobileclaw.skill.executor

import com.mobileclaw.skill.Skill
import com.mobileclaw.skill.SkillMeta
import com.mobileclaw.skill.SkillResult
import com.mobileclaw.skill.SkillType
import com.mobileclaw.skill.SkillParam
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull

/**
 * Executes whitelisted shell commands via ProcessBuilder.
 * Shell skills are NATIVE-only — cannot be generated by Meta-Skill.
 */
class ShellExecutor {

    private val allowedCommands = setOf(
        "ls", "cat", "grep", "find", "ps", "date", "uptime", "getprop",
        "am", "pm", "dumpsys",
    )

    suspend fun execute(command: String, args: List<String>): SkillResult {
        val cmd = command.trim().split(" ").first()
        if (cmd !in allowedCommands) {
            return SkillResult(success = false, output = "Command '$cmd' is not in the allowed list.")
        }
        return withContext(Dispatchers.IO) {
            val result = withTimeoutOrNull(5_000L) {
                runCatching {
                    val process = ProcessBuilder(listOf(command) + args)
                        .redirectErrorStream(true)
                        .start()
                    val output = process.inputStream.bufferedReader().readText().take(4096)
                    process.waitFor()
                    output
                }.fold(
                    onSuccess = { SkillResult(success = true, output = it) },
                    onFailure = { SkillResult(success = false, output = "Shell error: ${it.message}") }
                )
            }
            result ?: SkillResult(success = false, output = "Command timed out (5s)")
        }
    }
}

/** Builtin skill wrapping ShellExecutor for Agent use. */
class ShellSkill(private val executor: ShellExecutor = ShellExecutor()) : Skill {
    override val meta = SkillMeta(
        id = "shell",
        name = "Shell Command",
        description = "Runs a whitelisted shell command (ls, ps, getprop, am, pm, dumpsys, etc.) and returns output.",
        parameters = listOf(
            SkillParam("command", "string", "Command name (e.g. 'getprop')"),
            SkillParam("args", "string", "Space-separated arguments (optional)", required = false),
        ),
        type = SkillType.SHELL,
        injectionLevel = 1,
    )

    override suspend fun execute(params: Map<String, Any>): SkillResult {
        val command = params["command"] as? String
            ?: return SkillResult(false, "command is required")
        val args = (params["args"] as? String)?.split(" ")?.filter { it.isNotBlank() } ?: emptyList()
        return executor.execute(command, args)
    }
}
