package com.mobileclaw.skill

import android.content.Context
import android.os.Build
import com.google.gson.Gson
import com.mobileclaw.skill.executor.HttpSkillExecutor
import com.mobileclaw.skill.executor.PythonSkillExecutor
import java.io.File

/**
 * Loads dynamically-generated skills from {filesDir}/skills*.json at runtime.
 * Builtin (native) skills are registered separately via ClawApplication.
 */
class SkillLoader(
    private val context: Context,
    private val registry: SkillRegistry,
) {
    private val gson = Gson()
    private val skillsDir get() = File(context.filesDir, "skills").also { it.mkdirs() }

    fun loadAll() {
        skillsDir.listFiles { f -> f.extension == "json" }?.forEach { file ->
            runCatching { loadFile(file) }
                .onFailure { /* malformed skill file — skip silently */ }
        }
    }

    fun loadFile(file: File) {
        val def = gson.fromJson(file.readText(), SkillDefinition::class.java)
        validate(def)
        val skill = toSkill(def, file)
        registry.register(skill)
    }

    fun persist(def: SkillDefinition) {
        validate(def)
        val file = File(skillsDir, "${def.meta.id}.json")
        file.writeText(gson.toJson(def))
        loadFile(file)
    }

    fun delete(id: String) {
        File(skillsDir, "$id.json").delete()
        registry.unregister(id)
    }

    /** Promotes a dynamic skill from Level 2 to Level 1 and persists the change. */
    fun promote(id: String) {
        val file = File(skillsDir, "$id.json")
        require(file.exists()) { "Skill '$id' not found on disk" }
        val def = gson.fromJson(file.readText(), SkillDefinition::class.java)
        val promoted = def.copy(meta = def.meta.copy(injectionLevel = 1))
        file.writeText(gson.toJson(promoted))
        loadFile(file)
    }

    /** Returns all dynamic skill definitions currently stored on disk. */
    fun allDynamic(): List<SkillDefinition> =
        skillsDir.listFiles { f -> f.extension == "json" }
            ?.mapNotNull { file ->
                runCatching { gson.fromJson(file.readText(), SkillDefinition::class.java) }.getOrNull()
            } ?: emptyList()

    // --- Validation ---

    private fun validate(def: SkillDefinition) {
        require(def.meta.id.matches(Regex("[a-z0-9_]+"))) { "Skill id must be snake_case alphanumeric" }
        require(def.meta.name.isNotBlank()) { "Skill name is required" }
        require(def.meta.description.isNotBlank()) { "Skill description is required" }
        require(def.meta.type != SkillType.NATIVE) { "Cannot dynamically load NATIVE skills" }
        require(def.meta.type != SkillType.SHELL) { "SHELL skills cannot be generated by Meta-Skill" }
        require(def.meta.minApiLevel <= Build.VERSION.SDK_INT) {
            "Skill requires API ${def.meta.minApiLevel}, device is ${Build.VERSION.SDK_INT}"
        }
        if (def.meta.type == SkillType.PYTHON) {
            requireNotNull(def.script) { "Python skill must have a script" }
            validatePythonScript(def.script)
        }
        if (def.meta.type == SkillType.HTTP) {
            requireNotNull(def.httpConfig) { "HTTP skill must have executor_config" }
        }
    }

    // Modules that must not be imported at all (string or dotted form)
    private val blockedModules = setOf(
        "subprocess", "socket", "ctypes", "importlib", "os",
        "shutil", "multiprocessing", "threading", "signal",
        "pty", "termios", "fcntl", "resource", "mmap",
        "pickle", "shelve", "marshal",
    )

    // Built-in expressions that bypass import checks or execute arbitrary code
    private val blockedExpressions = setOf(
        "__import__", "__builtins__", "__class__", "__subclasses__",
        "compile(", "eval(", "exec(",
        "getattr(", "setattr(", "delattr(",
        "open(",
    )

    private fun validatePythonScript(script: String) {
        val lower = script.lowercase()
        // Reject blocked module imports
        blockedModules.forEach { mod ->
            require(!lower.contains("import $mod") && !lower.contains("from $mod ")) {
                "Python script imports blocked module: $mod"
            }
        }
        // Reject dangerous built-in expressions (checked case-sensitively on original script)
        blockedExpressions.forEach { expr ->
            require(!script.contains(expr)) {
                "Python script uses blocked expression: $expr"
            }
        }
    }

    private fun toSkill(def: SkillDefinition, file: File): Skill = when (def.meta.type) {
        SkillType.PYTHON -> PythonSkillExecutor(def.meta, def.script!!)
        SkillType.HTTP -> HttpSkillExecutor(def.meta, def.httpConfig!!)
        else -> throw IllegalArgumentException("Unsupported dynamic skill type: ${def.meta.type}")
    }
}

/** JSON-serializable skill definition stored on disk. */
data class SkillDefinition(
    val meta: SkillMeta,
    val script: String? = null,         // for PYTHON type
    val httpConfig: HttpSkillConfig? = null, // for HTTP type
)

data class HttpSkillConfig(
    val url: String,
    val method: String = "GET",
    val headers: Map<String, String> = emptyMap(),
    val paramsMapping: Map<String, String> = emptyMap(), // skill param name → query/body key
    // Optional: JSON path to extract image base64 from response (e.g. "data[0].b64_json")
    val imageResponsePath: String? = null,
    // Optional: JSON path to extract text output from response (e.g. "choices[0].text")
    val textResponsePath: String? = null,
)
