package com.mobileclaw.skill

import android.content.Context
import android.os.Build
import com.google.gson.Gson
import com.mobileclaw.skill.executor.HttpSkillExecutor
import com.mobileclaw.skill.executor.PythonSkillExecutor
import java.io.File

/**
 * Loads dynamically-generated skills from {filesDir}/skills*.json at runtime.
 * Builtin (native) skills are registered separately via ClawApplication.
 */
class SkillLoader(
    private val context: Context,
    private val registry: SkillRegistry,
) {
    private val gson = Gson()
    private val skillsDir get() = File(context.filesDir, "skills").also { it.mkdirs() }

    fun loadAll() {
        skillsDir.listFiles { f -> f.extension == "json" }?.forEach { file ->
            runCatching { loadFile(file) }
                .onFailure { /* malformed skill file — skip silently */ }
        }
    }

    fun loadFile(file: File) {
        val def = normalize(gson.fromJson(file.readText(), SkillDefinition::class.java))
        validate(def)
        val skill = toSkill(def, file)
        registry.register(skill)
    }

    fun persist(def: SkillDefinition) {
        validate(def)
        val file = File(skillsDir, "${def.meta.id}.json")
        file.writeText(gson.toJson(def))
        loadFile(file)
    }

    fun delete(id: String) {
        File(skillsDir, "$id.json").delete()
        registry.unregister(id)
    }

    /** Promotes a dynamic skill from Level 2 to Level 1 and persists the change. */
    fun promote(id: String) {
        val file = File(skillsDir, "$id.json")
        if (!file.exists()) return
        val def = normalize(gson.fromJson(file.readText(), SkillDefinition::class.java))
        val updated = def.copy(meta = def.meta.copy(injectionLevel = 1))
        runCatching { file.writeText(gson.toJson(updated)) }
        // Skip validate() — skill already passed validation at creation time
        runCatching { registry.register(toSkill(updated, file)) }
            .onFailure { registry.unregister(id) }
    }

    /** Demotes a dynamic skill from Level 1 back to Level 2 (on-demand). */
    fun demote(id: String) {
        val file = File(skillsDir, "$id.json")
        if (!file.exists()) return
        val def = normalize(gson.fromJson(file.readText(), SkillDefinition::class.java))
        val updated = def.copy(meta = def.meta.copy(injectionLevel = 2))
        runCatching { file.writeText(gson.toJson(updated)) }
        runCatching { registry.register(toSkill(updated, file)) }
            .onFailure { registry.unregister(id) }
    }

    /** Returns all dynamic skill definitions currently stored on disk. */
    fun allDynamic(): List<SkillDefinition> =
        skillsDir.listFiles { f -> f.extension == "json" }
            ?.mapNotNull { file ->
                runCatching { gson.fromJson(file.readText(), SkillDefinition::class.java) }.getOrNull()
            } ?: emptyList()

    // --- Normalization ---

    /**
     * Gson ignores Kotlin default values and can produce null for non-nullable List fields
     * when deserializing old JSON files that predate those fields. Fix nulls defensively.
     */
    @Suppress("SENSELESS_COMPARISON")
    private fun normalize(def: SkillDefinition): SkillDefinition {
        val m = def.meta
        return def.copy(
            meta = m.copy(
                tags       = if (m.tags == null) emptyList() else m.tags,
                parameters = if (m.parameters == null) emptyList() else m.parameters,
            ),
        )
    }

    // --- Validation ---

    private fun validate(def: SkillDefinition) {
        require(def.meta.id.matches(Regex("[a-z0-9_]+"))) { "Skill id must be snake_case alphanumeric" }
        require(def.meta.name.isNotBlank()) { "Skill name is required" }
        require(def.meta.description.isNotBlank()) { "Skill description is required" }
        require(def.meta.type != SkillType.NATIVE) { "Cannot dynamically load NATIVE skills" }
        require(def.meta.type != SkillType.SHELL) { "SHELL skills cannot be generated by Meta-Skill" }
        require(def.meta.minApiLevel <= Build.VERSION.SDK_INT) {
            "Skill requires API ${def.meta.minApiLevel}, device is ${Build.VERSION.SDK_INT}"
        }
        if (def.meta.type == SkillType.PYTHON) {
            requireNotNull(def.script) { "Python skill must have a script" }
            validatePythonScript(def.script)
        }
        if (def.meta.type == SkillType.HTTP) {
            requireNotNull(def.httpConfig) { "HTTP skill must have executor_config" }
        }
    }

    private fun validatePythonScript(script: String) {
        // No content-level restrictions — Python runs in Chaquopy's sandboxed interpreter.
        require(script.isNotBlank()) { "Python script must not be empty" }
    }

    /** Returns true if a skill with this ID is already installed as a dynamic skill. */
    fun isInstalled(id: String): Boolean = File(skillsDir, "$id.json").exists()

    private fun toSkill(def: SkillDefinition, file: File): Skill = when (def.meta.type) {
        SkillType.PYTHON -> PythonSkillExecutor(def.meta, def.script!!)
        SkillType.HTTP -> HttpSkillExecutor(def.meta, def.httpConfig!!)
        else -> throw IllegalArgumentException("Unsupported dynamic skill type: ${def.meta.type}")
    }
}

/** JSON-serializable skill definition stored on disk. */
data class SkillDefinition(
    val meta: SkillMeta,
    val script: String? = null,         // for PYTHON type
    val httpConfig: HttpSkillConfig? = null, // for HTTP type
)

data class HttpSkillConfig(
    val url: String,
    val method: String = "GET",
    val headers: Map<String, String> = emptyMap(),
    val paramsMapping: Map<String, String> = emptyMap(), // skill param name → query/body key
    // Optional: JSON path to extract image base64 from response (e.g. "data[0].b64_json")
    val imageResponsePath: String? = null,
    // Optional: JSON path to extract text output from response (e.g. "choices[0].text")
    val textResponsePath: String? = null,
)
