package com.mobileclaw.agent

/**
 * A Role bundles a persona (system prompt addendum), forced skill injection list,
 * and optional model override. The agent operates differently depending on the active role.
 */
data class Role(
    val id: String,
    val name: String,
    val description: String,
    val avatar: String,                         // emoji
    val systemPromptAddendum: String = "",
    val forcedSkillIds: List<String> = emptyList(),
    val modelOverride: String? = null,
    val preferredTaskTypes: List<TaskType> = emptyList(),
    val keywords: List<String> = emptyList(),
    val schedulerPriority: Int = 0,
    val isBuiltin: Boolean = false,
    val chatBubbleStyle: ChatBubbleStyle = ChatBubbleStyle(),
) {
    companion object {
        val DEFAULT = Role(
            id = "general",
            name = "通用助手",
            description = "按用户任务自动进入对应模式，不额外强制注入工具",
            avatar = "🦀",
            systemPromptAddendum = "Follow the current Task Mode strictly. Do not request or use tools outside the task's allowed skill set.",
            preferredTaskTypes = listOf(TaskType.CHAT, TaskType.GENERAL),
            keywords = listOf("聊天", "问答", "通用", "chat", "general"),
            isBuiltin = true,
        )

        val BUILTINS: List<Role> = listOf(
            DEFAULT,
            Role(
                id = "coder",
                name = "代码专家",
                description = "专注于编程、调试、脚本和自动化任务",
                avatar = "👨‍💻",
                systemPromptAddendum = "You are an expert software engineer. For code tasks, use only CODE_EXECUTION or FILE_CREATE tools allowed by the current Task Mode. Keep changes scoped, verify with builds/tests when possible, and report command results clearly. Do not operate the phone UI unless the task is classified as PHONE_CONTROL.",
                preferredTaskTypes = listOf(TaskType.CODE_EXECUTION, TaskType.FILE_CREATE),
                keywords = listOf("代码", "编程", "脚本", "调试", "编译", "bug", "shell", "python", "gradle"),
                isBuiltin = true,
            ),
            Role(
                id = "web_agent",
                name = "网络助手",
                description = "专注于网络搜索、信息抓取和网页浏览",
                avatar = "🌐",
                systemPromptAddendum = "You specialize in WEB_RESEARCH tasks. Use search/fetch/browse tools only when the current Task Mode allows them. Prefer source-backed answers, avoid phone UI control, and summarize findings concisely.",
                preferredTaskTypes = listOf(TaskType.WEB_RESEARCH),
                keywords = listOf("搜索", "查询", "网页", "资料", "新闻", "最新", "research", "search", "browse"),
                isBuiltin = true,
            ),
            Role(
                id = "phone_operator",
                name = "手机操控",
                description = "专注于控制 Android 界面、点击、滑动和应用操作",
                avatar = "📱",
                systemPromptAddendum = "You specialize in PHONE_CONTROL tasks. Use the observe -> act -> verify loop. Start with see_screen, use screenshot only when XML/accessibility nodes or markers are unusable, then take a concrete action before observing again. Prefer foreground phone control and pixel coordinates from the latest observation.",
                preferredTaskTypes = listOf(TaskType.PHONE_CONTROL),
                keywords = listOf("手机", "打开", "点击", "滑动", "输入", "长按", "屏幕", "app", "android"),
                isBuiltin = true,
            ),
            Role(
                id = "creator",
                name = "创意助手",
                description = "专注于原生页面、MiniAPP 程序、图片生成和内容创作",
                avatar = "🎨",
                systemPromptAddendum = "You specialize in IMAGE_GENERATION, APP_BUILD, and FILE_CREATE tasks. For page/dashboard/form/panel/screen requests, prefer ui_builder to create an AI Native Page. Use app_manager only for explicit app/mini-app/program/game or custom HTML/JS/Python/SQLite runtime needs. Never return raw code or HTML when a creation tool can create the artifact. For PPT/PPTX, Word/DOCX, Excel/XLSX, and PDF, always use generate_document and provide structured JSON content; never hand-write office files with create_file or Python libraries. Produce complete usable outputs instead of long raw content in chat.",
                preferredTaskTypes = listOf(TaskType.IMAGE_GENERATION, TaskType.APP_BUILD, TaskType.FILE_CREATE),
                keywords = listOf("图片", "画图", "图标", "视频", "页面", "原生页面", "ai页面", "仪表盘", "应用", "miniapp", "html", "文档", "文件", "生成"),
                isBuiltin = true,
            ),
            Role(
                id = "skill_admin",
                name = "技能管理员",
                description = "专注于检查、创建、安装和整理 skill",
                avatar = "🧩",
                systemPromptAddendum = "You specialize in SKILL_MANAGEMENT tasks. Inspect the current skill inventory before changing it. Keep new skills disabled or on-demand unless the user explicitly promotes them. Do not use phone, web, or code execution tools unless the current Task Mode allows them.",
                preferredTaskTypes = listOf(TaskType.SKILL_MANAGEMENT),
                keywords = listOf("skill", "技能", "能力", "安装", "创建技能", "技能市场"),
                isBuiltin = true,
            ),
            Role(
                id = "vpn_operator",
                name = "VPN 管理员",
                description = "专注于 VPN 开关、节点选择、订阅和连接状态诊断",
                avatar = "🔐",
                systemPromptAddendum = "You specialize in VPN_CONTROL tasks. Use vpn_control for start, stop, status, subscription, and proxy selection work. Do not operate the phone UI unless VPN permission or setup requires visible user action.",
                preferredTaskTypes = listOf(TaskType.VPN_CONTROL),
                keywords = listOf("vpn", "代理", "节点", "订阅", "全局", "连接", "mihomo", "clash"),
                isBuiltin = true,
            ),
        )
    }
}

data class ChatBubbleStyle(
    val preset: String = "minimal",
    val renderer: String = "native",
    val htmlTemplate: String = "",
    val htmlHeightDp: Int = 160,
    val htmlAllowJs: Boolean = false,
    val htmlAllowNetwork: Boolean = true,
    val htmlTransparent: Boolean = true,
    val backgroundColor: String = "",
    val backgroundImage: String = "",
    val textColor: String = "",
    val borderColor: String = "",
    val accentColor: String = "",
    val radiusDp: Int = 18,
    val radiusTopStartDp: Int = -1,
    val radiusTopEndDp: Int = -1,
    val radiusBottomEndDp: Int = -1,
    val radiusBottomStartDp: Int = -1,
    val tail: String = "soft",
    val pattern: String = "none",
    val decoration: String = "none",
    val decorationText: String = "",
    val decorationPosition: String = "top_end",
    val decorationAnimation: String = "none",
    val decorationSizeDp: Int = 14,
    val decorations: List<ChatBubbleDecoration> = emptyList(),
    val gradient: List<String> = emptyList(),
    val animation: String = "none",
    val emotion: String = "neutral",
    val fontFamily: String = "system",
    val fontWeight: String = "regular",
    val textAnimation: String = "none",
    val fontSizeSp: Int = 14,
    val lineHeightSp: Int = 20,
    val paddingHorizontalDp: Int = 12,
    val paddingVerticalDp: Int = 8,
    val shadow: String = "none",
    val shadowColor: String = "",
    val shadowAlpha: Float = -1f,
    val shadowElevationDp: Int = -1,
    val shadowOffsetXDp: Int = 0,
    val shadowOffsetYDp: Int = 0,
    val imageMode: String = "cover",
    val schemaVersion: Int = 2,
)

data class ChatBubbleDecoration(
    val type: String = "none",
    val text: String = "",
    val position: String = "top_end",
    val x: Float = -1f,
    val y: Float = -1f,
    val animation: String = "none",
    val sizeDp: Int = 14,
    val color: String = "",
    val alpha: Float = -1f,
)
